### ISSUE TITLE
git-delete-merged-on-remote fails

### ISSUE THREAD

**Issue by ssiccha** [fingolfin/git-scripts#1]
This is what happens:
```
git-delete-merged-on-remote origin
git push --delete origin HEAD create_stats ss/info
error: unable to delete 'HEAD': remote ref does not exist
error: failed to push some refs to 'git@github.com:ssiccha/GaussPar'
```
If I then do `git push --delete origin create_stats ss/info` manually everything is fine.
The script somehow thinks that `HEAD` also is a branch that should be deleted?

**Comment by fingolfin** [comment]
Weird. Some details please? Git version, OS (if Linux: distro, version), output of `git branch` and `git remote -v`

**Comment by fingolfin** [comment]
Ahh, wait, you are using `origin`. OK, then I think I can reproduce the issue.

**Comment by fingolfin** [comment]
Please `git pull` this repo and try again

**Comment by ssiccha** [comment]
Works like a charm! :)
